# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [8]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [9]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [10]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [18]:
np.random.rand(1)

array([0.34961182])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [21]:
np.random.randn(25)

array([-1.15890208, -0.89402214,  1.12562294,  0.37806795, -0.31299386,
       -1.01926504, -0.00197608, -0.20064865, -0.7089875 , -0.09973428,
       -0.49593057,  1.07115439,  1.02852679,  1.28556402, -0.18752301,
        0.71026577,  0.21965962,  0.9319259 , -1.63614092, -0.08012955,
       -1.1266303 , -0.39192183, -0.05917121,  1.32639857,  1.62800288])

#### Create the following matrix:

In [24]:
np.arange(1, 101).reshape(10, 10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [27]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [31]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
mat[2 : , 1 : ]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [33]:
mat[3, -1]

20

20

In [55]:
#mat[ : 3, 1].reshape(3, 1) or
mat[ : 3, 1 : 2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [39]:
mat[-1]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [41]:
mat[-2 :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [46]:
#mat.sum() or
#sum(sum(mat)) or
sum(mat).sum()

325

#### Get the standard deviation of the values in mat

In [47]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [51]:
#sum(mat) or
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

## Assign the following values
theta_0 = 15; 
theta_1 = 0.2; 
variance=1.2

In [4]:
theta_0 = 15; theta_1 = 0.2; variance = 1.2

## Generate 100 points uniform randomly in range [-50,50] and assign it to X_0

In [125]:
X_0 = np.random.uniform(-50, 51, 100)
X_0

array([ 23.17806005,  35.75949646, -34.65895138, -48.56749344,
       -13.52242753, -30.5667931 ,  49.10842203,  11.02925008,
       -11.87941533,  -7.79796832,  44.88539279,  39.12182851,
        17.33615696, -47.37495455,  25.84046915,  -0.63601561,
       -23.18341967,  31.66090257,  28.09933353,  41.5008099 ,
       -34.88276788,  36.31948219,   5.14480858,   0.83106024,
        -6.72998245, -34.78057295,   7.88729515,   7.59584209,
       -42.63421571, -30.96385977,  49.02953814,  22.10337174,
        22.37273801, -27.99381561, -43.33301065, -48.65078399,
       -24.69121344,   7.38425895,  12.11198568,  19.23723233,
        21.9366023 ,  22.93168227,   7.77298052,  32.76951569,
        -4.72147103,  48.79308865,  -5.02792086, -15.66994286,
         9.17718861, -15.81954346, -39.70863303,  31.41049434,
        10.1453746 ,  -3.73617562, -33.50808815, -11.93931854,
       -25.77569363,  48.15139925, -46.38576348,  47.82670069,
        30.89192785,  11.29462576,   2.44703783,  -5.88

## Generate respective y_i normally distributed around theta_0 + theta_1 * x line ('x' are values of X_0) with variance=1.2

In [130]:
y_ = []
for i in range(len(X_0)):
    y_ = np.append(y_, (variance * np.random.randn(1) + (theta_0 + theta_1 * X_0[i])))
y_

array([19.18769439, 20.167685  ,  8.24052732,  5.44176628, 14.71567913,
        8.68805887, 26.91684241, 19.54862158, 12.37080188, 13.01682634,
       24.05285901, 23.18970477, 20.37789045,  5.56813322, 19.82732671,
       12.63911905, 10.71322645, 21.74076788, 20.13911432, 24.97201337,
        7.43722379, 20.2054105 , 16.2745937 , 12.01796379, 14.34507708,
        8.84232164, 16.53487283, 14.46717885,  8.30279662,  7.5318842 ,
       25.64601614, 19.09332174, 18.65221117,  8.71371276,  7.27870595,
        5.52137831,  9.20720596, 16.73920083, 17.47928863, 18.04369052,
       18.57389871, 18.82552079, 16.17091318, 21.06464353, 13.47569899,
       25.19970268, 15.84344809, 10.46428755, 16.57192939, 13.03682108,
        7.87539646, 21.40636425, 16.40816065, 17.57443364,  9.88587981,
       13.76672827, 11.12423275, 26.69058889,  4.88014428, 26.27564608,
       20.80301043, 16.15921666, 14.75819383, 14.65245978, 24.425684  ,
       12.07674157, 17.37135526, 13.26837785, 14.56563763,  5.61

## Convert X_0 into array(if it is not) and add 1 from the left to each row

In [129]:
#it should look smth like this
# (1,x1)
# (1,x2)
# .
# .
# .
new_X_0 = []
length = len(X_0)
new_X_0 = np.append(np.ones(length).reshape(length, 1), X_0.reshape(length, 1), axis = 1)
new_X_0

array([[  1.        ,  23.17806005],
       [  1.        ,  35.75949646],
       [  1.        , -34.65895138],
       [  1.        , -48.56749344],
       [  1.        , -13.52242753],
       [  1.        , -30.5667931 ],
       [  1.        ,  49.10842203],
       [  1.        ,  11.02925008],
       [  1.        , -11.87941533],
       [  1.        ,  -7.79796832],
       [  1.        ,  44.88539279],
       [  1.        ,  39.12182851],
       [  1.        ,  17.33615696],
       [  1.        , -47.37495455],
       [  1.        ,  25.84046915],
       [  1.        ,  -0.63601561],
       [  1.        , -23.18341967],
       [  1.        ,  31.66090257],
       [  1.        ,  28.09933353],
       [  1.        ,  41.5008099 ],
       [  1.        , -34.88276788],
       [  1.        ,  36.31948219],
       [  1.        ,   5.14480858],
       [  1.        ,   0.83106024],
       [  1.        ,  -6.72998245],
       [  1.        , -34.78057295],
       [  1.        ,   7.88729515],
 

# Great Job!